### ISSUE TITLE
Cookie div is too large and shifts the page down when it appears

### ISSUE THREAD

**Issue by SeshanPillay25** [SeshanPillay25/fixing-userinyerface#3]

**Comment by Ipshu41** [comment]
Hi I would like to take a shot at fixing this.

**Comment by Ipshu41** [comment]
@SeshanPillay25 found a solution, tried to push the branch but it gives me -
remote: Permission to SeshanPillay25/fixing-userinyerface.git denied to Ipshu41.
fatal: unable to access 'https://github.com/SeshanPillay25/fixing-userinyerface.git/': The requested URL returned error: 403
